name: firmador_movil
description: "Sistema de Firma Digital Autorizada - FIIIDT"
publish_to: "none"

# El 2.0.1 es lo que ve el usuario. El +3 es lo que le dice a Android que es una actualización.
version: 2.0.1+4

environment:
  sdk: ^3.12.0-113.2.beta

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  file_picker: ^10.3.10
  syncfusion_flutter_pdfviewer: ^32.2.9
  http: ^1.6.0
  path_provider: ^2.1.5 # <-- Indispensable para las rutas seguras en iOS
  shared_preferences: ^2.5.4

  # --- LIBRERÍAS DE BIOMETRÍA Y SEGURIDAD ---
  local_auth: ^2.1.8
  flutter_secure_storage: ^9.0.0
  permission_handler: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  # Declaración de recursos para los logos institucionales
  assets:
    - assets/img/

# --- CONFIGURACIÓN DEL ÍCONO DE LA APP ---
flutter_launcher_icons:
  android: true
  ios: true # Lo activamos para que también genere el ícono en tu nuevo iPhone
  image_path: "assets/img/SOFII.png"
